name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: ./mvnw clean package --no-transfer-progress

      - name: Run Tests
        run: ./mvnw test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t 041124310679.dkr.ecr.eu-west-2.amazonaws.com/sentiment-api:latest .

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names sentiment-api || \
          aws ecr create-repository --repository-name sentiment-api

      - name: Push to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 041124310679.dkr.ecr.eu-west-2.amazonaws.com
          docker push 041124310679.dkr.ecr.eu-west-2.amazonaws.com/sentiment-api:latest
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name sentiment-cluster --region eu-west-2

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yaml

      - name: Check Health
        run: |
          set -e
            kubectl rollout status deployment/sentiment-api
            kubectl get pods
            EXTERNAL_IP=$(kubectl get svc sentiment-api -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            echo "EXTERNAL_IP: $EXTERNAL_IP"
            curl --retry 5 --retry-delay 10 http://$EXTERNAL_IP/actuator/prometheus
